# Generated by Django 5.1.1 on 2025-04-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customer_customers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
    ]
