# Generated by Django 5.1.1 on 2025-04-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uincom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='description',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='spell_type',
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_use',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
