# Generated by Django 5.1.1 on 2025-04-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uincom', '0002_remove_spell_description_remove_spell_spell_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleShopProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'StyleShop Product',
                'verbose_name_plural': 'StyleShop Products',
            },
        ),
        migrations.CreateModel(
            name='TechMartProduct',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'TechMart Product',
                'verbose_name_plural': 'TechMart Products',
            },
        ),
    ]
