# Generated by Django 5.1.1 on 2025-04-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uincom', '0003_styleshopproduct_techmartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('image', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Spell',
        ),
        migrations.DeleteModel(
            name='StyleShopProduct',
        ),
        migrations.DeleteModel(
            name='TechMartProduct',
        ),
    ]
